### ISSUE TITLE
Where's the comments?

### ISSUE THREAD

**Issue by shyamalschandra** [dicarlolab/CORnet#1]
Who wrote this?  Definitely not some sort of "real" software engineer.  You call this MIT work.

Before you tell me to do this myself, look in the mirror and remove the GPL license and replace with MIT license.

**Comment by shyamalschandra** [comment]
Excuse me, why did you close this issue?  No response.  What type of answer was that?

**Comment by NickleDave** [comment]
https://snarky.ca/the-social-contract-of-open-source/
