### ISSUE TITLE
A litter question about CORblock_S

### ISSUE THREAD

**Issue by violetcodet** [dicarlolab/CORnet#10]
I think the key point of this paper is that the CORblock_S can be learned for serval times in the one epoch. 
So, how can you guarantee the conv2d in each for-loop is always the same one?
In my experience, when building a network using such a for-loop, all convolutions will with different weights.
It is equivalent to building a relatively long ordinary network.

**Comment by qbilius** [comment]
I think it all depends on how you define your model. In our case, we define the weights of all convolutions once (in the `__init__`), but then call the convolutional operators several times. So when you look at the parameters file, you'll only see the following convolutional weights for V2 block, for instance:

```
'module.V2.conv_input.weight',
'module.V2.skip.weight',
'module.V2.conv1.weight',
'module.V2.conv2.weight',
'module.V2.conv3.weight'
```

For each convolution, there is only a single weight stored.

Perhaps you could share a code example of how you were thinking this could cause different weights to be learned for the same convolutional layer?
