### ISSUE TITLE
What is the Brain-Score of CORnet-S?

### ISSUE THREAD

**Issue by rgeirhos** [dicarlolab/CORnet#13]
http://www.brain-score.org/ lists the average Brain-Score of CORnet-S as .379; however the Brain-Score reported in https://papers.nips.cc/paper/9441-brain-like-object-recognition-with-high-performing-shallow-recurrent-anns.pdf lists a Brain-Score of .471 instead on page 6. Would you mind clarifying which one is correct and where the discrepancy comes from?

**Comment by mschrimpf** [comment]
The NeurIPS paper used the initial version of our benchmarks (https://github.com/brain-score/brain-score/releases/tag/v0.2) where the V4 and IT benchmarks contained images of all variations as described in Majaj & Hong et al. 2015. The current version of the benchmarks on the website only uses the more difficult images (variation 6 in the paper; all models fare worse on predicting these neural recordings making for more of a challenge) which allowed us to publicly release recordings for the other images (variations 0 and 3; https://github.com/brain-score/brain-score/blob/master/brainscore/benchmarks/public_benchmarks.py). 

So the current version of the benchmarks shown on the website is in our view correct *at the moment* -- there might still be updates of existing benchmarks, but we will clearly mark those version differences (https://github.com/brain-score/brain-score.web/pull/12).

**Comment by rgeirhos** [comment]
I see, thanks for your detailed answer!
