### ISSUE TITLE
How to get Brain-Score?

### ISSUE THREAD

**Issue by donghaiwang** [dicarlolab/CORnet#15]
After I get the output features of test image (eg. CORnet-S_decoder_avgpool_feats.npy), how to get the [Brain-Score](https://github.com/brain-score/brain-score). Can you show me the detailed steps? Thanks.

**Comment by qbilius** [comment]
The Brain-Score repo you referred to and the repos it links have some explanations how to compute Brain-Score from model features. I agree those are not very straightforward to follow, but that's all we have at the moment.

**Comment by mschrimpf** [comment]
To get the full set of scores, you would submit the model to the Brain-Score platform. See [here](https://github.com/brain-score/sample-model-submission/) on how to do that and [here](https://github.com/brain-score/candidate_models/blob/ad840bf990ec4d94b44c3782ead38b43eff68c58/candidate_models/model_commitments/cornets.py#L25) for how this is implemented for CORnet. There are also examples for scoring models on e.g. the public benchmarks [here](https://github.com/brain-score/brain-score/blob/master/examples/benchmarks.ipynb) for a generic model and [here](https://github.com/brain-score/candidate_models/blob/master/examples/score-model.ipynb) for a pre-defined model.
