### ISSUE TITLE
CORnet doesn't complain but doesn't do anything either

### ISSUE THREAD

**Issue by vwadia** [dicarlolab/CORnet#16]
Hey guys, 

When I try to run the model out of the box nothing happens. I have realized that it works on some stimulus sets but not others. I figured this had to do with the images I want to get features being grayscale with only 1 channel. I modified them to have 3 identical channels but all I get is this, with my output path being empty. Any idea what the issue is? My apologies I'm new to all this!

![issueScrnshot](https://user-images.githubusercontent.com/35933522/149245744-a8b25dcc-6494-4b5e-9598-994b72822298.PNG)

**Comment by mschrimpf** [comment]
Hi @vwadia,

this is odd indeed. Your command line arguments all look fine to me.
It looks like it fails without iterating over the images in your `500Stimuli` directory, but failing to e.g. load the image should print an error message (https://github.com/dicarlolab/CORnet/blob/master/run.py#L220-L223).
Is it possible for you to debug and step through the code line by line to find out where it seems to exit?

**Comment by vwadia** [comment]
Hi @mschrimpf! Thank you for the quick response. Some further digging led me to realize that the issue was with PIL trying to convert TIFFs. So line 221

im = Image.open(fname).convert('RGB')

would fail which would break out of the loop so there would be nothing to save. I changed the code to

img = cv2.imread(fname)
im_pil = Image.fromarray(img)
im = im_pil.convert('RGB')

And it now runs fine. Apparently PIL has had issues with tiffs for a while even with the new plugin.

**Comment by mschrimpf** [comment]
Thanks for posting your solution and an explanation, I'm sure this will be helpful to others too!
