### ISSUE TITLE
fire complains despite success

### ISSUE THREAD

**Issue by mschrimpf** [dicarlolab/CORnet#5]
Run command: `python run.py test --restore_path cornet_z_epoch25.pth.tar - --model Z --data_path my_images -o .`

Output:

    100%|██████████| 136/136 [00:04<00:00, 30.35it/s]
    Fire trace:
    1. Initial component
    2. Accessed property "test"
    3. Called routine "test" (/Users/apurvaratanmurty/dev/CORnet/run.py:187)
    4. ('Could not consume arg:', '--model')
    
    Type:        NoneType
    String form: None
    
    Usage:       run.py test --restore_path cornet_z_epoch25.pth.tar -

However, the features file was created successfully.

**Comment by qbilius** [comment]
This is expected but confusing behavior which occurs sure to my use of both
global and local (function-specific) flags. Any ideas how to do it better
(with or without fire)?

**Comment by mschrimpf** [comment]
We might be able to change `sys.argv` after global argparse parsing, e.g.

    args, remaining_args= parser.parse_known_args()
    sys.argv = sys.argv[:1] + remaining_args

Another option would be to write our own [subparsers](https://docs.python.org/3/library/argparse.html#sub-commands).
